import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by Home'
}

export default async function Home() {
  console.log('Home', typeof window === 'undefined')

  return (
    <>
      <h1>Hello World</h1>
      <div className="">
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem labore
        deserunt accusamus, tenetur exercitationem officia voluptatum pariatur
        dolore? Vitae facere ratione non dolorum cumque atque exercitationem
        architecto minus blanditiis totam.
      </div>
    </>
  )
}